package rules;

import com.sam.Loan.Agent;
import com.sam.Loan.ApplicantInfo;
import com.sam.Loan.LoanInfo;
import com.sam.Loan.Person;

rule "Test on IDE"
	when
		$ai : ApplicantInfo(ofAge == true)
	then
		System.out.println("Hello you are of age");
		drools.setFocus("Hello");
end

rule "Test fucus"
ruleflow-group "Hello"
	when
	
	then
		System.out.println("Focus working");
		//testing 2
end

rule "new rule"
	when
		$ai : ApplicantInfo(ofAge == true)
	then
		System.out.println("Hello  World");
end

rule "Great Tax Score"
ruleflow-group "approve"
activation-group "approval"
salience 10
	when
		$ai : ApplicantInfo()
		$p : Person(taxScore >= 800) from $ai.person
	then
		System.out.println("You are approved");
end